server:
  servlet: 
    context-path: /
  port: 8000
# Spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.187:3306/cat_danmu1?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMutiQueries=true
    username: admin
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #    druid:
    initialSize: 20
    minIdle: 10
    maxActive: 200
    #配置获取连接等待超时的时间
    maxWait: 6000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  redis: 
    database: 3
    host: 192.168.1.187
    port: 6379
    password: 123456
    timeout: 100000
    jedis:
      pool:
        max-active: 500
        max-idle: 10
        max-wait: 10000
        
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yz.entity
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #dialect: mysql
    #plugins: com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql日志到控制台

#登录服地址
loginUrl: http://127.0.0.1:10205/catDanmuLoginServer


