server:
  servlet: 
    context-path: /
  port: 8000
# Spring配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.187:3306/cat_danmu1?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&allowMutiQueries=true
    username: admin
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    #    druid:
    initialSize: 20
    minIdle: 10
    maxActive: 200
    #配置获取连接等待超时的时间
    maxWait: 6000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
  redis: 
    database: 3
    host: 192.168.1.187
    port: 6379
    password: 123456
    timeout: 100000
    jedis:
      pool:
        max-active: 500
        max-idle: 10
        max-wait: 10000
        
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yz.pojo.entity
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #dialect: mysql
    #plugins: com.baomidou.mybatisplus.extension.plugins.PaginationInterceptor
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql日志到控制台

#登录服地址
loginUrl: http://127.0.0.1:10205/catDanmuLoginServer

#抖音配置  
#appid
douyinAppid: tta757d1ea3860461110
#app私钥
douyinSecret: c029aac9614e68005ff6c42ef8053b7cb62adeab
#应用私钥
douyinApplicationSecret: t+CcvJlnJBozB8tn4koC/Hy395WhKxF/BkA03rilcNLNQmY53UoH/SwIKN8Z+DXr4fUWAlfBnL+j/QZ2IT2r/ZYdfrOC7yXCMTA5ujEKO8oLSc4/tQSBoAR4XcGrKVVrLalYsiKNAgMBAAECggEBAKLAIoNFfbx6IB8GvfGJxUlrFkf9BYlHCEXJoAgD4P/RkHIVsVqLS46hGrwHE+t5mu9u9MTSkIDekhRy7vxEpDE5dOSK0OAnn8AjAlqU4g9hNhzBpqTAEF0K72/W5ROxin0xF/B03MOM1LqGo1pw5gJn+tV0B9P+cJ4I2CuAyydW/9lWK0YUHZQHZDk/Sep1OGl9aM3JsjUVEdm1bNWL7GtjvTZAtE10gnxBGh5wgBUu1Kl0/BQ+8wWLvvHq8pj95hKhvp15v8bnHaFY48SceW52abIU2qZuUd92vhIISQsm6Kc6Nm9o1Lkk6bdnRslpmsTkOEs2GqHiVIqFuAsC2SECgYEA1YSn/ry3CXq1lbyYfpqFKzCng0mqymKd54O0D2TLjhcl8TUFYS1oqWRUb9d9lsZQ6ga/+JbIxLzwkHUbdN+EnprrSHbzanOGcJRP9VcRjjj3yUO56l6ucQjrS3dx54tCX6+ghPdWW9qgTvG0FfTGtrCiIMhGA+QjC5yG2cQfrxkCgYEAxVRdj/xxmufvpIQcO0iOxCQsImBwbeZPZjKTheZ9VtvPJoX8t3I0g98GxDkKlA4KAOIbANhRwO7Yj02kHktikYzalNLAvQblint+x+dr0dhgKk6maB+tQs/PErLzLO5bSTfjFUiwgWQDEz2DCOTD+xz8Tf1faQWuwR2MOEsHIZUCgYB/zdOwyszUw7qFUkoFHgCwBYN/Nk0grz7NISxaOn8NIhX390CtFj0bh45zE418/l/YdQnbhoXOHTnxfeddYZ1EQn6q9WhmQ5gpMt1ZgTBk7PyEYCGcg+fuiOQuW+S2L8ke9UUj0djDSm3CUzL0IXwARmIFNVuTYK8JeDvPhXFhoQKBgQCnj2YLeA93vG8vwca/SHOCdjzLzBxsFd9iJpxCXWAdO3WBftEDbQTO3bk/MjibU/iGm3jWlNmG/MoDlahA2T6P3Y1WRkfHu2161DbpxMc3X4b5JeQEErHrQ87QUAhSJOx7FevMDPdkR+qckeUMzkTknM5Z40b7RQoJje+ddYhOqQKBgQC9XjE00QCPUB8nCK2CeyjY5PXvJeVVilnOplU6Gn8ndijiPTy2Qh+EDmwrrx0YfyXyKbEZ9oIzSw9Enq/s2ck9YY4yPVDj9EHilTDFQ0csRRjMV+JrobuiikKFBlZIFktJE2CBtQPd4+z8jxCxqdLl1vcKsrM9OjH3urjWXuBTRA==
#应用公钥
douyinApplicationPublicSecret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyaUMPlCnWLWlgMHANCCvlv5LtrrCt4dfFL3JkNVxgAuMC3P+U2hsqLR8ACs9RnkfOchGVSSlrcXthMKZ2GTPKwJpJEPNgZhFX1yyM3WOgfeGb8v48mMAINhiN2Eovu/EQT7dYof2mfHDZdtEo2gQ5PWOmFT8pI5IwhWY4uib+bL/Dh1aGR47WqP7UImnZobA37KYjjdVqSg7mQtMYxEgflof8pO678G4O4Uy7VTox61ae9xLgA1WAMqwIY+L/kj0VOXCXwO2+UgfJcaum1RTEJFLl+EoOJKqziB6q3hXpf69EzG0QVl6nhyWYcvYB/JP5hxp45NKjs0btphuDGI4IwIDAQAB
#平台私钥
douyinPlatformSecret: yuanzililiang
#平台公钥
douyinPlatformPublicSecret: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyaUMPlCnWLWlgMHANCCvlv5LtrrCt4dfFL3JkNVxgAuMC3P+U2hsqLR8ACs9RnkfOchGVSSlrcXthMKZ2GTPKwJpJEPNgZhFX1yyM3WOgfeGb8v48mMAINhiN2Eovu/EQT7dYof2mfHDZdtEo2gQ5PWOmFT8pI5IwhWY4uib+bL/Dh1aGR47WqP7UImnZobA37KYjjdVqSg7mQtMYxEgflof8pO678G4O4Uy7VTox61ae9xLgA1WAMqwIY+L/kj0VOXCXwO2+UgfJcaum1RTEJFLl+EoOJKqziB6q3hXpf69EzG0QVl6nhyWYcvYB/JP5hxp45NKjs0btphuDGI4IwIDAQAB


